window.H2T_CONTENT = {
  en: {
    brand: {
      name: "H2T",
      service: "Lighting Service",
      title: "H2T Lighting Service",
      badge: "Available for projects",
      logo: "logos/h2t-main-logo.png",
      logoAlt: "H2T Lighting Service logo",
    },
    nav: {
      menu1: "About Us",
      menu2: "Service",
      menu3: "Portfolio",
      menu4: "Tools",
      cta: "Contact",
      openMenu: "Open menu",
    },
    hero: {
      line1: "We keep",
      lineGreen: "light",
      line3: "in sync with your show.",
      sub: "H2T Lighting Service provides professional lighting solutions - from design concepts to live stage operation.",
      btn1: "Explore Services",
      btn2: "Contact Now ->",
    },
    stats: [
      { num: "18", label: "Years of experience" },
      { num: "800+", label: "Completed shows" },
      { num: "20+", label: "Clients" },
    ],
    services: [
      {
        name: "Design",
        desc: "Develop lighting concepts tailored to the space and show content. Includes fixture plots, technical drawings, and optimized equipment selection - shaping a clear and cohesive visual direction.",
        image: "services/lighting-design.jpg",
        imageAlt: "Lighting Design image",
        tags: ["Concept", "Light Plot", "Gear List Order"],
      },
      {
        name: "Program",
        desc: "Build professional show files on grandMA3 and grandMA2 - including patching, presets, cue lists, and effects. Optimized for each part of the show.",
        image: "services/lighting-program.jpg",
        imageAlt: "Lighting Program image",
        tags: ["grandMA3", "grandMA2"],
      },
      {
        name: "PreViz",
        desc: "Realistic 3D simulation of the entire lighting environment before construction. Identify issues early and reduce rehearsal time.",
        image: "services/lighting-previz.jpg",
        imageAlt: "Lighting Previz image",
        tags: ["3D Visualize", "Concept Demo Video"],
      },
      {
        name: "Perform",
        desc: "Professional show operation with reliable execution, responsive control, and strong understanding of music and performance.",
        image: "services/lighting-operate.jpg",
        imageAlt: "Lighting Operate image",
        tags: [],
      },
      {
        name: "Training",
        desc: "Hands-on training for lighting operators and creative teams. Covers console workflow, show structure, cue building, and practical troubleshooting.",
        image: "services/lighting-training.jpg",
        imageAlt: "Lighting Training image",
        mediaScale: 0.75,
        tags: ["Console Workflow", "Cue Build", "Troubleshooting"],
      },
    ],
    portfolio: {
      title: "Selected work",
      titleAccent: "Portfolio",
      desc: "A quick overview of shows and visual directions developed by H2T.",
      items: [
        { title: "Concert Stage", meta: "Live show", image: "portfolio/concert-stage.jpg", imageAlt: "Concert Stage portfolio image" },
        { title: "Brand Launch", meta: "Corporate event", image: "portfolio/brand-launch.jpg", imageAlt: "Brand Launch portfolio image" },
        { title: "Tour Visuals", meta: "Touring production", image: "portfolio/tour-visuals.jpg", imageAlt: "Tour Visuals portfolio image" },
        { title: "Music Festival", meta: "Festival production", image: "portfolio/music-festival.jpg", imageAlt: "Music Festival portfolio image" },
        { title: "Government Festival", meta: "Government event", image: "portfolio/government-festival.jpg", imageAlt: "Government Festival portfolio image" },
      ],
    },
    tools: [
      { abbr: "MA3", name: "GrandMA3", type: "Console", logo: "logos/ma3.png" },
      { abbr: "VW", name: "Vectorworks", type: "Design", logo: "logos/Vectorworks.png" },
      { abbr: "CAP", name: "Capture", type: "Previz", logo: "logos/capture.png" },
      { abbr: "DEP", name: "Depence R4", type: "Previz", logo: "logos/dep.png" },
      { abbr: "RES", name: "Resolume Arena", type: "Media Server", logo: "logos/resolume.png" },
      { abbr: "MAD", name: "Madrix", type: "Console", logo: "logos/madrix.png" },
      { abbr: "+", name: "And more...", type: "", logo: "logos/plus.png" },
    ],
    about: {
      titleLine1: "Passionate about light,",
      titleGreen: "professional",
      titleLine3: "operation.",
      body: "H2T Lighting Service was founded by industry professionals with over 18 years of real-world experience - shaped by hundreds of live shows, not theory. We understand the pressure of live performance, the demands of production, and the expectations of the audience.",
      values: [
        { icon: "✦", title: "Technical Excellence", desc: "We invest deeply in technology - from precise previsualization to reliable production workflows." },
        { icon: "◈", title: "Creative Collaboration", desc: "Great lighting comes from shared understanding. We listen, align, and work closely with directors and producers." },
        { icon: "▶", title: "Reliability on Stage", desc: "When the lights go on, there is no room for error. H2T ensures full readiness before every show." },
      ],
      team: [
        { photo: "photos/founder.jpg", name: "Trong Bui", role: "Founder", subrole: "Certified MA Lighting Trainer (grandMA3)" },
        { photo: "photos/account.jpg", name: "Hoang Nguyen", role: "Account" },
        { photo: "photos/programmer.jpg", name: "Huong Vu", role: "Lighting Programmer" },
        { photo: "photos/previz.jpg", name: "Tinh Vo", role: "Previz Specialist" },
      ],
    },
    why: [
      { title: "Full-service, one team", desc: "From the first drawing to the final night of the tour - one team throughout, with no handovers." },
      { title: "Previz before risks", desc: "Every show is previewed in a 3D environment. Issues are identified before real rigging begins." },
      { title: "Real battle-tested experience", desc: "Hundreds of shows - from concerts to corporate events. We know what can happen, and we prepare for it." },
      { title: "Clear communication", desc: "Transparent timelines, regular updates. You always know where your show stands." },
      { title: "Long-term investment", desc: "We continuously upgrade our skills and technology. You always work with a team at the forefront of the industry." },
    ],
    contact: {
      titleLine1: "Let's make",
      titleGreen: "the next",
      titleLine3: "show together.",
      desc: "Whether you're planning a big concert or an intimate event - tell us about it. We'll get back to you shortly.",
      email: "admin@h2tteam.com",
      phone: "+84 (0) 973607 867",
      facebook: "https://www.facebook.com/h2tlighting",
      instagram: "@h2tteamvn",
    },
    footer: {
      copy: "© 2025 H2T Lighting Service · Ho Chi Minh City, Vietnam",
    },
    labels: {
      servicesChip: "Services",
      servicesTitleLine1: "From concept",
      servicesTitleLine3: "to live stage",
      servicesTitleAccent: "live stage",
      servicesDesc: "We accompany you through the entire lifecycle of a production - design, programming, preview, and operation. One team, all stages.",
      portfolioChip: "Portfolio",
      toolsChip: "Tools",
      toolsTitleLine1: "Industry-grade",
      toolsTitleAccent: "tools",
      toolsDesc: "H2T uses industry-standard software and hardware. All tools are fully licensed and carefully selected to best serve each stage of production.",
      aboutChip: "About Us",
      teamHeading: "The Team",
      teamNote: "* Team members and portrait photos will be updated later",
      whyChip: "Why H2T?",
      whyTitleLine1: "Not just turning on lights.",
      whyTitleAccent: "Keeping every cue",
      whyTitleLine3: "in sync.",
      contactChip: "Contact",
      emailLabel: "Email",
      phoneLabel: "Phone",
      facebookLabel: "Facebook",
      instagramLabel: "Instagram",
      localeLabel: "Language",
    },
  },
  vi: {
    brand: {
      name: "H2T",
      service: "Dịch vụ ánh sáng toàn diện cho ngành biểu diễn",
      title: "H2T Lighting Service",
      badge: "Sẵn sàng cho dự án mới",
      logo: "logos/h2t-main-logo.png",
      logoAlt: "Logo H2T Lighting Service",
    },
    nav: {
      menu1: "Giới thiệu",
      menu2: "Dịch vụ",
      menu3: "Dự án",
      menu4: "Công cụ",
      cta: "Liên hệ",
      openMenu: "Mở menu",
    },
    hero: {
      line1: "Đồng bộ",
      lineGreen: "ánh sáng",
      line3: "cùng từng cue của show.",
      sub: "H2T Lighting Service cung cấp giải pháp ánh sáng chuyên nghiệp, từ ý tưởng thiết kế đến vận hành sân khấu trực tiếp.",
      btn1: "Xem dịch vụ",
      btn2: "Liên hệ ngay ->",
    },
    stats: [
      { num: "18", label: "Năm kinh nghiệm" },
      { num: "800+", label: "Show đã thực hiện" },
      { num: "20+", label: "Khách hàng" },
    ],
    services: [
      {
        name: "Thiết kế",
        desc: "Phát triển ý tưởng ánh sáng phù hợp với không gian và nội dung chương trình. Bao gồm bản vẽ ánh sáng, list thiết bị tối ưu để tạo nên định hướng thị giác rõ ràng, đồng nhất.",
        image: "services/lighting-design.jpg",
        imageAlt: "Hình ảnh dịch vụ thiết kế ánh sáng",
        tags: ["Concept", "Light Plot", "Gear List"],
      },
      {
        name: "Lập trình",
        desc: "Xây dựng showfile chuyên nghiệp trên grandMA3 và grandMA2, bao gồm patching, preset, cue list và effect. Mọi thứ được tối ưu theo từng nhu cầu của chương trình và khách hàng.",
        image: "services/lighting-program.jpg",
        imageAlt: "Hình ảnh dịch vụ lập trình ánh sáng",
        tags: ["grandMA3", "grandMA2"],
      },
      {
        name: "Mô Phỏng tiền kỳ",
        desc: "Mô phỏng 3D toàn bộ môi trường ánh sáng trước khi thi công. Giúp phát hiện vấn đề sớm và rút ngắn thời gian rehearsal.",
        image: "services/lighting-previz.jpg",
        imageAlt: "Hình ảnh dịch vụ previz ánh sáng",
        tags: ["3D Visualize", "Demo Video"],
      },
      {
        name: "Vận hành",
        desc: "Vận hành show chuyên nghiệp, với khả năng xử lý ổn định, phản xạ nhanh và cảm nhận tốt về âm nhạc lẫn tiết mục trình diễn.",
        image: "services/lighting-operate.jpg",
        imageAlt: "Hình ảnh dịch vụ vận hành show",
        tags: [],
      },
      {
        name: "Đào tạo",
        desc: "Đào tạo thực chiến cho lighting operator và các đội ngũ sáng tạo. Nội dung bao gồm workflow console, cấu trúc show, dựng cue và xử lý sự cố trong thực tế.",
        image: "services/lighting-training.jpg",
        imageAlt: "Hình ảnh dịch vụ đào tạo ánh sáng",
        mediaScale: 0.75,
        tags: ["Console Workflow", "Cue Build", "Troubleshooting"],
      },
    ],
    portfolio: {
      title: "Dự án tiêu biểu",
      titleAccent: "Portfolio",
      desc: "Tổng quan nhanh về các show do H2T đảm nhận.",
      items: [
        { title: "Sân khấu concert", meta: "Live show", image: "portfolio/concert-stage.jpg", imageAlt: "Hình dự án sân khấu concert" },
        { title: "Sự kiện nhãn hàng", meta: "Sự kiện doanh nghiệp", image: "portfolio/brand-launch.jpg", imageAlt: "Hình dự án ra mắt thương hiệu" },
        { title: "Tour visuals", meta: "Touring production", image: "portfolio/tour-visuals.jpg", imageAlt: "Hình dự án touring production" },
        { title: "Lễ hội âm nhạc", meta: "Festival production", image: "portfolio/music-festival.jpg", imageAlt: "Hình dự án music festival" },
        { title: "Lễ hội Nhà Nước", meta: "Sự kiện nhà nước", image: "portfolio/government-festival.jpg", imageAlt: "Hình dự án government festival" },
      ],
    },
    tools: [
      { abbr: "MA3", name: "GrandMA3", type: "Console", logo: "logos/ma3.png" },
      { abbr: "VW", name: "Vectorworks", type: "Design", logo: "logos/Vectorworks.png" },
      { abbr: "CAP", name: "Capture", type: "Previz", logo: "logos/capture.png" },
      { abbr: "DEP", name: "Depence R4", type: "Previz", logo: "logos/dep.png" },
      { abbr: "RES", name: "Resolume Arena", type: "Media Server", logo: "logos/resolume.png" },
      { abbr: "MAD", name: "Madrix", type: "Console", logo: "logos/madrix.png" },
      { abbr: "+", name: "Và nhiều hơn nữa", type: "", logo: "logos/plus.png" },
    ],
    about: {
      titleLine1: "Đam mê với ánh sáng,",
      titleGreen: "vận hành",
      titleLine3: "chuyên nghiệp.",
      body: "H2T Lighting Service được tạo nên bởi những con người với hơn 18 năm kinh nghiệm thực chiến, được trui rèn qua hàng trăm live show, chứ không phải lý thuyết khô khan. Chúng tôi hiểu áp lực của sân khấu, yêu cầu của production và kỳ vọng của khán giả.",
      values: [
        { icon: "✦", title: "Trình độ vững vàng", desc: "Chúng tôi đầu tư sâu vào công nghệ, từ previsualization chính xác, đến quy trình vận hành thực tế ổn định." },
        { icon: "◈", title: "Đồng hành sáng tạo", desc: "Ánh sáng tốt đến từ sự thấu hiểu chung. Chúng tôi lắng nghe, phát triển ý tưởng và làm việc sát với đạo diễn cùng các nhà sản xuất." },
        { icon: "▶", title: "Tin cậy trên sân khấu", desc: "Khi đèn sáng lên, không có chỗ cho sai sót. H2T đảm bảo mọi show đều sẵn sàng trước giờ G." },
      ],
      team: [
        { photo: "photos/founder.jpg", name: "Trong Bui", role: "Founder", subrole: "Certified MA Lighting Trainer (grandMA3)" },
        { photo: "photos/account.jpg", name: "Hoang Nguyen", role: "Account" },
        { photo: "photos/programmer.jpg", name: "Huong Vu", role: "Lighting Programmer" },
        { photo: "photos/previz.jpg", name: "Tinh Vo", role: "Previz Specialist" },
      ],
    },
    why: [
      { title: "Dịch vụ toàn diện, một đội ngũ", desc: "Từ bản vẽ đầu tiên đến đêm cuối cùng của tour, một đội ngũ đồng hành xuyên suốt, không chia tách khâu thực hiện." },
      { title: "Lường trước các rủi ro", desc: "Mỗi show đều được preview trong môi trường 3D. Vấn đề được nhìn ra trước khi thi công thực tế." },
      { title: "Kinh nghiệm thực chiến", desc: "Hàng trăm show, từ concert đến sự kiện doanh nghiệp. Chúng tôi biết điều gì có thể xảy ra và luôn chuẩn bị trước cho nó." },
      { title: "Giao tiếp rõ ràng", desc: "Timeline minh bạch, cập nhật đều đặn. Bạn luôn biết show đang ở giai đoạn nào." },
      { title: "Đầu tư dài hạn", desc: "Chúng tôi liên tục nâng cấp kỹ năng và công nghệ. Bạn luôn làm việc với một đội ngũ đang tiến về phía trước." },
    ],
    contact: {
      titleLine1: "Cùng nhau tạo nên",
      titleGreen: "show tiếp theo",
      titleLine3: "thật ấn tượng.",
      desc: "Dù là concert lớn ngoài trời hay sự kiện trong nhà với quy mô vừa phải, hãy cho chúng tôi biết nhu cầu của bạn.",
      email: "admin@h2tteam.com",
      phone: "+84 (0) 973607 867",
      facebook: "https://www.facebook.com/h2tlighting",
      instagram: "@h2tteamvn",
    },
    footer: {
      copy: "© 2025 H2T Lighting Service · TP. Ho Chi Minh, Việt Nam",
    },
    labels: {
      servicesChip: "Dịch vụ",
      servicesTitleLine1: "Từ concept",
      servicesTitleLine3: "đến sân khấu live",
      servicesTitleAccent: "sân khấu live",
      servicesDesc: "Chúng tôi đồng hành xuyên suốt quá trình sản xuất của một chương trình: thiết kế, lập trình, preview và vận hành. Một đội ngũ, trọn quy trình.",
      portfolioChip: "Dự án",
      toolsChip: "Công cụ",
      toolsTitleLine1: "Bộ công cụ",
      toolsTitleAccent: "chuyên nghiệp",
      toolsDesc: "H2T sử dụng phần mềm và thiết bị theo chuẩn ngành. Tất cả công cụ đều có bản quyền đầy đủ và được chọn lựa triển khai kỹ cho từng giai đoạn sản xuất.",
      aboutChip: "Giới thiệu",
      teamHeading: "Đội ngũ",
      teamNote: "* Thành viên và ảnh chân dung sẽ được cập nhật sau",
      whyChip: "Vì sao H2T?",
      whyTitleLine1: "Không chỉ là bật tắt đèn.",
      whyTitleAccent: "Giữ mọi cue",
      whyTitleLine3: "luôn đồng bộ.",
      contactChip: "Liên hệ",
      emailLabel: "Email",
      phoneLabel: "Điện thoại",
      facebookLabel: "Facebook",
      instagramLabel: "Instagram",
      localeLabel: "Ngôn ngữ",
    },
  },
};